#!/bin/bash

Usage(){
    echo `basename $0` "[apply time]"
    echo "      [apply time]: Immediate or OnReset"
    echo ""
    echo "Get update service apply time"
    exit 1
}

# basic check
basic_check

# run command
res=`curl -k -H "X-Auth-Token: $token" -X GET https://${bmc_ip}/redfish/v1/UpdateService 2>/dev/null`

echo $res | grep -o "\"ApplyTime\": \".*\" "
