#!/bin/bash

Usage(){
    echo `basename $0` "[xyz item] [xyz attr]"
    echo "   ex: /xyz/openbmc_project/software/attr/FieldModeEnabled"
    echo "   xyz item: software"
    echo "   xyz attr: FieldModeEnabled"
    echo ""
    echo "Get xyz rest API attriute"
    exit 1
}

# basic check
basic_check

# mode option/check
if [ -z "${1}" -o -z "${2}" ]; then
  echo "Please set up xyz item and attribute!"
  Usage
fi
xyz_item="$1"
xyz_attr="$2"

# run command
url="https://${bmc_ip}/xyz/openbmc_project/${xyz_item}/attr/${xyz_attr}"
res=`curl -k -H "X-Auth-Token: $token" -X GET ${url} 2>/dev/null`

echo $res
